# Generated by Django 4.2.1 on 2023-08-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='About_me',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='profile',
            name='previous_work',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
