# Generated by Django 4.2.1 on 2023-09-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfApp', '0004_alter_profile_email_alter_profile_previous_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pin',
        ),
        migrations.AddField(
            model_name='profile',
            name='Interest',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='certificate',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='pic.jpg', upload_to='profilepic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
