# Generated by Django 4.2.1 on 2023-09-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfApp', '0005_remove_profile_pin_profile_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='certificate',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
