# Generated by Django 4.2.1 on 2023-10-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfApp', '0004_alter_profile_dob'),
        ('pdfApp', '0009_alter_profile_interest_alter_profile_certificate_and_more'),
    ]

    operations = [
    ]
