# Generated by Django 4.2.1 on 2023-12-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college_end',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college_start',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school_date',
        ),
    ]
