# Generated by Django 4.2.1 on 2024-08-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_image', models.ImageField(upload_to='template_images/')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='resume_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cvapp.resumetemplate'),
        ),
    ]
