# Generated by Django 4.2.1 on 2024-08-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvapp', '0002_resumetemplate_profile_resume_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
